### ISSUE TITLE
Linear Combination

### ISSUE THREAD

**Issue by LeanaNeuber** [LeanaNeuber/AkkaActorParty#3]
- [ ] Decide upon algorithm and understand it
- [ ] Implement algorithm
- [ ] Parallelize if possible

**Comment by SebastianSchmidl** [comment]
may be useful: https://en.wikipedia.org/wiki/Linear_combination

**Comment by LeanaNeuber** [comment]
If we calculate the sum of all 42 six-digit numbers and divide it by two, we "just" need to find a combination of our numbers that result in this number.. right?
Might be an approach to look at...
See https://de.wikipedia.org/wiki/Teilsummenproblem and https://de.wikipedia.org/wiki/Branch-and-Bound
